dev env/app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from app import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
    path('catalog/', include("goobs.urls", namespace="catalog")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dev env/app/goobs/urls.py
from django.urls import path
from goobs import views


app_name = "goobs"

urlpatterns = [
    path('', views.catalog, name='catalog'),
    path('product/<slug:product_slug>/', views.product, name='product'),
]

dev env/app/main/urls.py
from django.urls import path
from main import views

urlpatterns = [
    path('', views.index, name='index')
]

dev env/app/goobs/models.py
from django.db import models

class Products(models.Model):
    name = models.CharField(max_length=100, unique=True, verbose_name="Название")
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name="URL")
    description = models.TextField(blank=True, null=True, verbose_name="Описание")
    image = models.ImageField(upload_to="goobs_image", blank=True, null=True, verbose_name="Изображение")
    price = models.DecimalField(default=0.00, max_digits=8, decimal_places=2, verbose_name="Цена")
    discount = models.DecimalField(default=0.00, max_digits=8, decimal_places=2, verbose_name="Скидка в процентах")

    class Mets:
        db_table = "product"
        verbose_name  = "Продукты"
        verbose_name_plural = "Продукт"

    def __str__(self):
        return self.name
    
    def sell_price(self):
        if self.discount:
            return round(self.price - self.price * self.discount / 100, 2)
        
        return self.price

dev env/app/main/models.py
from django.db import models

# Create your models here.

dev env/app/goobs/views.py
from django.shortcuts import render

from goobs.models import Products

def catalog(request):
    
    goobs = Products.objects.all()

    context = {
        "title": "Home - Каталог",
        "goobs": goobs,
    }
    return render(request, "goobs/catalog.html", context)

def product(request, product_slug):

    product = Products.objects.get(slug=product_slug)

    context = {
        "product": product
    }
    return render(request, "goobs/product.html", context=context)

dev env/app/main/views.py
from django.shortcuts import render

def index(request):
    context = {
        'title': 'Home',
        'content': 'Главная страница',
    }
    return render(request, 'main/index.html', context)

dev env/app/goobs/templates/goobs/catalog.html
{% extends 'main/base.html' %}
{% load static%}
{% block title %}{{'Главная страница'}}{% endblock %}

{% block content %}
<body1>
    <div class="maincontainer">
        <div class="leftbar">
        
        </div>
        <div class="container">

            {% for product in goobs%}
                <div class="card">
                    {% if product.image %}
                    <img src="{{ product.image.url }}" class="card-img-top" alt="logo">
                    {% endif %}
                <div class="card-body">
                    <a href="{% url "catalog:product" product.slug %}">
                        <p class="card-title">{{ product.name }}</span></p>
                    </a>
                    <p class="card-text">{{ product.description }}</p>
                    <div class="d-flex justify-content-between">
                        {% if product.discount %}
                        <p><s>{{product.price}}</s> $</p>
                        <p><strong>{{ product.sell_price }}</strong></p>
                        <span class="badge bg-warning text-dark">
                            <strong>Скидка {{product.discount}} %</strong>
                        </span>
                        {% else %}
                            <p><strong>{{ product.price }}</strong></p>
                        {% endif %}
                    </div>
                </div>
                </div>
            {% endfor %}
            
        </div>
    </div>
</body1>


{% endblock %}

dev env/app/goobs/templates/goobs/product.html
{% extends 'main/base.html' %}
{% load static%}
{% block title %}{{'Главная страница'}}{% endblock %}

{% block content %}
<body1>
    <div class="maincontainer">
        <div class="leftbar">
        
        </div>
        <div class="container-prod">
            <div class="card-prod">
                <img src="{{product.image.url}}" class="card-img-top-prod" alt="logo">
                <div class="card-body">
                    <h2 class="card-title">{{product.name}}</h2>
                    <p class="card-text">{{product.description}}</p>
                    <div class="body_2">
                        <div class="body_price">
                            {% if product.discount %}
                        <p><s>{{product.price}}</s> $</p>
                        <p><strong>{{ product.sell_price }}</strong></p>
                        <span class="badge bg-warning text-dark">
                            <strong>Скидка {{product.discount}} %</strong>
                        </span>
                        {% else %}
                            <p><strong>{{ product.price }}</strong></p>
                        {% endif %}
                        </div>
                        <a href="#" class="btn btn-dark add-to-cart">Забронировать столик</a>
                    </div>
                </div>
            </div>
            
        </div>
    </div>
</body1>


{% endblock %}

dev env/app/main/templates/main/base.html
{% load static%}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
</head>
<body>
    <aside>
        <img src="{% static 'main/img/logo.jpg' %}" alt="logo">
        <span class="logo">KoFFeLOVE</span>
        <h3>Навигация</h3>
        <ul>
            <a href="{%url "index"%}"><li><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-house" viewBox="0 0 16 16">
            <path d="M8.707 1.5a1 1 0 0 0-1.414 0L.646 8.146a.5.5 0 0 0 .708.708L2 8.207V13.5A1.5 1.5 0 0 0 3.5 15h9a1.5 1.5 0 0 0 1.5-1.5V8.207l.646.647a.5.5 0 0 0 .708-.708L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.707 1.5ZM13 7.207V13.5a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5V7.207l5-5 5 5Z"/>
            </svg> Главная</li></a>
            <a href="/about"><li><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-info-square" viewBox="0 0 16 16">
            <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
            <path d="m8.93 6.588-2.29.287-.082.38.45.083c.294.07.352.176.288.469l-.738 3.468c-.194.897.105 1.319.808 1.319.545 0 1.178-.252 1.465-.598l.088-.416c-.2.176-.492.246-.686.246-.275 0-.375-.193-.304-.533L8.93 6.588zM9 4.5a1 1 0 1 1-2 0 1 1 0 0 1 2 0z"/>
            </svg> Про отдых </li></a>
            <a href="/contact"><li><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-telephone" viewBox="0 0 16 16">
            <path d="M3.654 1.328a.678.678 0 0 0-1.015-.063L1.605 2.3c-.483.484-.661 1.169-.45 1.77a17.568 17.568 0 0 0 4.168 6.608 17.569 17.569 0 0 0 6.608 4.168c.601.211 1.286.033 1.77-.45l1.034-1.034a.678.678 0 0 0-.063-1.015l-2.307-1.794a.678.678 0 0 0-.58-.122l-2.19.547a1.745 1.745 0 0 1-1.657-.459L5.482 8.062a1.745 1.745 0 0 1-.46-1.657l.548-2.19a.678.678 0 0 0-.122-.58L3.654 1.328zM1.884.511a1.745 1.745 0 0 1 2.612.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.678.678 0 0 0 .178.643l2.457 2.457a.678.678 0 0 0 .644.178l2.189-.547a1.745 1.745 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.634 18.634 0 0 1-7.01-4.42 18.634 18.634 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877L1.885.511z"/>
            </svg> Контакты </li></a>
            <a href="{% url "goobs:catalog" %}"><li><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-shop" viewBox="0 0 16 16">
                <path d="M2.97 1.35A1 1 0 0 1 3.73 1h8.54a1 1 0 0 1 .76.35l2.609 3.044A1.5 1.5 0 0 1 16 5.37v.255a2.375 2.375 0 0 1-4.25 1.458A2.37 2.37 0 0 1 9.875 8 2.37 2.37 0 0 1 8 7.083 2.37 2.37 0 0 1 6.125 8a2.37 2.37 0 0 1-1.875-.917A2.375 2.375 0 0 1 0 5.625V5.37a1.5 1.5 0 0 1 .361-.976zm1.78 4.275a1.375 1.375 0 0 0 2.75 0 .5.5 0 0 1 1 0 1.375 1.375 0 0 0 2.75 0 .5.5 0 0 1 1 0 1.375 1.375 0 1 0 2.75 0V5.37a.5.5 0 0 0-.12-.325L12.27 2H3.73L1.12 5.045A.5.5 0 0 0 1 5.37v.255a1.375 1.375 0 0 0 2.75 0 .5.5 0 0 1 1 0M1.5 8.5A.5.5 0 0 1 2 9v6h1v-5a1 1 0 0 1 1-1h3a1 1 0 0 1 1 1v5h6V9a.5.5 0 0 1 1 0v6h.5a.5.5 0 0 1 0 1H.5a.5.5 0 0 1 0-1H1V9a.5.5 0 0 1 .5-.5M4 15h3v-5H4zm5-5a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v3a1 1 0 0 1-1 1h-2a1 1 0 0 1-1-1zm3 0h-2v3h2z"/>
              </svg> Магазин </li></a>
            <a href="/review"><li><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-vcard" viewBox="0 0 16 16">
            <path d="M5 8a2 2 0 1 0 0-4 2 2 0 0 0 0 4Zm4-2.5a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 0 1h-4a.5.5 0 0 1-.5-.5ZM9 8a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 0 1h-4A.5.5 0 0 1 9 8Zm1 2.5a.5.5 0 0 1 .5-.5h3a.5.5 0 0 1 0 1h-3a.5.5 0 0 1-.5-.5Z"/><path d="M2 2a2 2 0 0 0-2 2v8a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V4a2 2 0 0 0-2-2H2ZM1 4a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1H8.96c.026-.163.04-.33.04-.5C9 10.567 7.21 9 5 9c-2.086 0-3.8 1.398-3.984 3.181A1.006 1.006 0 0 1 1 12V4Z"/>
            </svg> Личный кабинет </li></a>
        </ul>

        <form class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success text-white" type="submit">Поиск</button>
        </form>
        <style>

          a {

          text-decoration: none;

          }

        </style>
    </aside>

        
    {% block content %}
    
    {% endblock %}

</body>
</html>

dev env/app/main/templates/main/index.html
{% extends 'main/base.html' %}
{% load static%}
{% block title %}{{'Главная страница'}}{% endblock %}

{% block content %}



{% endblock %}